<a href="https://colab.research.google.com/github/clemuss14430/MIC-CC-ODEM-EAN/blob/main/03_logistics_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FASE 3 — Logística**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

BASE_PATH = '/content/drive/MyDrive/MIC_CC'
FASE3_PATH = f'{BASE_PATH}/Fase3_Logistica'

folders = [
    FASE3_PATH,
    f'{FASE3_PATH}/raw_data',        # datos crudos recolectados por Laura
    f'{FASE3_PATH}/processed_data',  # datasets validados y limpios
    f'{FASE3_PATH}/outputs',         # tablas finales para Power BI
    f'{FASE3_PATH}/evidence'         # capturas, PDFs, fuentes de respaldo
]

for f in folders:
    os.makedirs(f, exist_ok=True)
    print(f'✓ Creada: {f}')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
import pandas as pd

top10_productos = pd.DataFrame([
    {"rank": 1,  "hs6": "090111", "producto": "Café sin tostar o descafeinar",        "vcr_prom": 4.95,  "valor_prom_usd_mm": 235.79},
    {"rank": 2,  "hs6": "270112", "producto": "Carbón bituminoso",                    "vcr_prom": 1.43,  "valor_prom_usd_mm": 137.17},
    {"rank": 3,  "hs6": "080450", "producto": "Guayabas, mangos y mangostanes",        "vcr_prom": 27.18, "valor_prom_usd_mm": 5.44},
    {"rank": 4,  "hs6": "060319", "producto": "Flores frescas (otras)",                "vcr_prom": 1.61,  "valor_prom_usd_mm": 27.60},
    {"rank": 5,  "hs6": "300432", "producto": "Medicamentos corticosteroides",         "vcr_prom": 15.01, "valor_prom_usd_mm": 3.96},
    {"rank": 6,  "hs6": "611596", "producto": "Medias de fibra sintética",             "vcr_prom": 16.06, "valor_prom_usd_mm": 1.80},
    {"rank": 7,  "hs6": "730792", "producto": "Accesorios de tubería (hierro)",        "vcr_prom": 9.99,  "valor_prom_usd_mm": 8.59},
    {"rank": 8,  "hs6": "030482", "producto": "Filetes de trucha congelada",           "vcr_prom": 13.09, "valor_prom_usd_mm": 0.89},
    {"rank": 9,  "hs6": "200819", "producto": "Nueces y semillas procesadas",          "vcr_prom": 12.29, "valor_prom_usd_mm": 0.54},
    {"rank": 10, "hs6": "060311", "producto": "Rosas frescas",                          "vcr_prom": 1.98,  "valor_prom_usd_mm": 11.34},
])

top10_productos.to_csv(f'{FASE3_PATH}/processed_data/top10_productos.csv', index=False)
top10_productos

   rank     hs6                        producto  vcr_prom  valor_prom_usd_mm
0     1  090111   Café sin tostar o descafeinar      4.95             235.79
1     2  270112               Carbón bituminoso      1.43             137.17
2     3  080450  Guayabas, mangos y mangostanes     27.18               5.44
3     4  060319          Flores frescas (otras)      1.61              27.60
4     5  300432   Medicamentos corticosteroides     15.01               3.96
5     6  611596       Medias de fibra sintética     16.06               1.80
6     7  730792  Accesorios de tubería (hierro)      9.99               8.59
7     8  030482     Filetes de trucha congelada     13.09               0.89
8     9  200819    Nueces y semillas procesadas     12.29               0.54
9    10  060311                   Rosas frescas      1.98              11.34

In [ ]:
columnas_dataset_maestro = [
    "hs6", "producto",
    "ruta",                          # "CTG-MTL" | "CTG-YVR"
    "flete_usd_teu_min", "flete_usd_teu_max", "flete_usd_teu_avg", "naviera",
    "transito_dias_min", "transito_dias_max", "transito_dias_avg",
    "handling_origen_usd_teu",       # Cartagena (SPRC/Contecar)
    "handling_destino_usd_teu",      # Montreal o Vancouver
    "transporte_interno_usd_ton",    # planta -> puerto CTG
    "seguro_pct_valor_mercancia",
    "incoterm",                      # FOB | CIF | DAP
    "fuente", "fecha_descarga", "url_evidencia"
]

dataset_maestro = pd.DataFrame(columns=columnas_dataset_maestro)
dataset_maestro.to_csv(f'{FASE3_PATH}/processed_data/dataset_maestro_logistico.csv', index=False)

print("Esquema maestro creado con", len(columnas_dataset_maestro), "columnas")
dataset_maestro

Esquema maestro creado con 18 columnas

Empty DataFrame
Columns: [hs6, producto, ruta, flete_usd_teu_min, flete_usd_teu_max, flete_usd_teu_avg, naviera, transito_dias_min, transito_dias_max, transito_dias_avg, handling_origen_usd_teu, handling_destino_usd_teu, transporte_interno_usd_ton, seguro_pct_valor_mercancia, incoterm, fuente, fecha_descarga, url_evidencia]
Index: []

In [ ]:
import pandas as pd
import os

BASE_PATH = '/content/drive/MyDrive/MIC_CC'
FASE3_PATH = f'{BASE_PATH}/Fase3_Logistica'

# Ensure the target directory exists
os.makedirs(f'{FASE3_PATH}/raw_data', exist_ok=True)

# Plantilla vacía con las columnas exactas que Laura debe llenar
plantilla_fletes = pd.DataFrame(columns=[
    "ruta",              # "CTG-MTL" o "CTG-YVR" (solo estos dos valores válidos)
    "naviera",            # ej: "Maersk", "MSC", "Hapag-Lloyd"
    "tarifa_usd_teu",     # número, ej: 2100
    "tipo_contenedor",    # "20ft" o "40ft"
    "fecha_cotizacion",   # fecha en que se consultó la tarifa (no la fecha del viaje)
    "fuente",             # "Freightos" o "Baltic Exchange"
    "url_evidencia",      # link directo o nota de cómo se obtuvo
    "observaciones"       # cualquier nota relevante (ej: "tarifa spot, sin contrato")
])

plantilla_fletes.to_excel(f'{FASE3_PATH}/raw_data/A1_plantilla_fletes_LAURA.xlsx', index=False)
print("Plantilla creada. Subir a Google Sheets para que Laura la edite colaborativamente.")

Plantilla creada. Subir a Google Sheets para que Laura la edite colaborativamente.

In [ ]:
def validar_fletes(filepath):
    df = pd.read_excel(filepath)
    errores = []

    # Preprocesar la columna tarifa_usd_teu para asegurar que sea numérica
    # Remover caracteres no numéricos como '$', ',', espacios, etc.
    df['tarifa_usd_teu'] = df['tarifa_usd_teu'].astype(str).str.replace(r'[^\d.]', '', regex=True)
    df['tarifa_usd_teu'] = pd.to_numeric(df['tarifa_usd_teu'], errors='coerce')

    # Regla 1: rutas válidas
    rutas_validas = {"CTG-MTL", "CTG-YVR"}
    rutas_invalidas = set(df["ruta"].dropna().unique()) - rutas_validas
    if rutas_invalidas:
        errores.append(f"Rutas inválidas encontradas: {rutas_invalidas}")

    # Regla 2: mínimo 3 navieras por ruta
    navieras_por_ruta = df.groupby("ruta")["naviera"].nunique()
    for ruta, n in navieras_por_ruta.items():
        if n < 3:
            errores.append(f"Ruta {ruta} tiene solo {n} navieras (mínimo 3 requerido)")

    # Regla 3: tarifa numérica y positiva
    # Después del preprocesamiento, verificar si hay NaNs introducidos por 'coerce'
    if df['tarifa_usd_teu'].isnull().any():
        errores.append("Columna tarifa_usd_teu contiene valores que no pudieron ser convertidos a numéricos")
    elif (df["tarifa_usd_teu"] <= 0).any():
        errores.append("Hay tarifas con valor 0 o negativo")

    # Regla 4: sin filas sin fuente
    if df["fuente"].isna().any() or df["url_evidencia"].isna().any():
        errores.append("Hay filas sin fuente o sin url_evidencia documentada")

    if errores:
        print("❌ VALIDACIÓN FALLIDA:")
        for e in errores:
            print(f"  - {e}")
        return False
    else:
        print("✅ Validación exitosa. Datos listos para integrar.")
        return True

# Uso (cuando Laura entregue):
validar_fletes(f'{FASE3_PATH}/raw_data/A1_plantilla_fletes_LAURA.xlsx')

❌ VALIDACIÓN FALLIDA:
  - Rutas inválidas encontradas: {'Vancouver CA - Cartagena CO', 'Montreal CA - Cartagena CO', 'Cartagena CO - Vancouver CA ', 'Cartagena CO - Montreal CA '}
  - Ruta Cartagena CO - Montreal CA  tiene solo 1 navieras (mínimo 3 requerido)
  - Ruta Cartagena CO - Vancouver CA  tiene solo 1 navieras (mínimo 3 requerido)
  - Ruta Montreal CA - Cartagena CO tiene solo 1 navieras (mínimo 3 requerido)
  - Ruta Vancouver CA - Cartagena CO tiene solo 1 navieras (mínimo 3 requerido)

False

In [ ]:
import pandas as pd
import numpy as np
import os

# Cargar el archivo
df_raw = pd.read_excel(f'{FASE3_PATH}/raw_data/A1_plantilla_fletes_LAURA.xlsx')

print("=== DIAGNÓSTICO INICIAL ===")
print(f"Filas totales: {len(df_raw)}")
print(f"Rutas encontradas: {df_raw['ruta'].unique().tolist()}")
print(f"Navieras por ruta:")
print(df_raw.groupby('ruta')['naviera'].value_counts())
print(f"\nFecha de cotización: {df_raw['fecha_cotizacion'].iloc[0]}")

=== DIAGNÓSTICO INICIAL ===
Filas totales: 12
Rutas encontradas: ['Cartagena CO - Montreal CA ', 'Montreal CA - Cartagena CO', 'Cartagena CO - Vancouver CA ', 'Vancouver CA - Cartagena CO']
Navieras por ruta:
ruta                          naviera
Cartagena CO - Montreal CA    CMA CGM          6
Cartagena CO - Vancouver CA   Hapag-Lloyd      2
Montreal CA - Cartagena CO    CMA CGM          2
Vancouver CA - Cartagena CO   Sin designar     2
Name: count, dtype: int64

Fecha de cotización: 2026-06-24 00:00:00

In [ ]:
# Tabla de mapeo: nombre SeaRates → código interno + dirección
MAPA_RUTAS = {
    "Cartagena CO - Montreal CA ":  {"codigo": "CTG-MTL", "direccion": "exportacion"},
    "Cartagena CO - Montreal CA":   {"codigo": "CTG-MTL", "direccion": "exportacion"},
    "Cartagena CO - Vancouver CA ": {"codigo": "CTG-YVR", "direccion": "exportacion"},
    "Cartagena CO - Vancouver CA":  {"codigo": "CTG-YVR", "direccion": "exportacion"},
    "Montreal CA - Cartagena CO":   {"codigo": "MTL-CTG", "direccion": "importacion"},
    "Montreal CA - Cartagena CO ":  {"codigo": "MTL-CTG", "direccion": "importacion"},
    "Vancouver CA - Cartagena CO":  {"codigo": "YVR-CTG", "direccion": "importacion"},
    "Vancouver CA - Cartagena CO ": {"codigo": "YVR-CTG", "direccion": "importacion"},
}

df_norm = df_raw.copy()

# Aplicar normalización
df_norm["ruta_codigo"] = df_norm["ruta"].map(
    lambda x: MAPA_RUTAS.get(x, {}).get("codigo", "DESCONOCIDA")
)
df_norm["direccion"] = df_norm["ruta"].map(
    lambda x: MAPA_RUTAS.get(x, {}).get("direccion", "desconocida")
)

# Filtrar solo exportación
df_export = df_norm[df_norm["direccion"] == "exportacion"].copy()

# Limpiar columna contenedor
df_export["tipo_contenedor"] = df_export["tipo_contenedor"].str.strip().str.replace(" ", "")

# Asegurar fecha como string limpio
df_export["fecha_cotizacion"] = pd.to_datetime(df_export["fecha_cotizacion"]).dt.strftime("%Y-%m-%d")

print(f"Filas exportación (válidas): {len(df_export)}")
print(df_export[["ruta_codigo", "naviera", "tarifa_usd_teu", "tipo_contenedor", "fecha_cotizacion"]].to_string())

Filas exportación (válidas): 8
   ruta_codigo      naviera  tarifa_usd_teu tipo_contenedor fecha_cotizacion
0      CTG-MTL      CMA CGM            1018          20pies       2026-06-24
1      CTG-MTL      CMA CGM            1036          20pies       2026-06-24
2      CTG-MTL      CMA CGM            1083          20pies       2026-06-24
4      CTG-YVR  Hapag-Lloyd            5281          20pies       2026-06-24
6      CTG-MTL      CMA CGM            1286          40pies       2026-06-24
7      CTG-MTL      CMA CGM            1369          40pies       2026-06-24
8      CTG-MTL      CMA CGM            1393          40pies       2026-06-24
10     CTG-YVR  Hapag-Lloyd            4610          40pies       2026-06-24

In [ ]:
# Factor de normalización: 20ft = 1 TEU; 40ft ≈ 1.7 TEU (estándar industria)
FACTOR_TEU = {
    "20pies": 1.0,
    "40pies": 1.7
}

def normalizar_a_teu(row):
    factor = FACTOR_TEU.get(row["tipo_contenedor"], 1.0)
    return round(row["tarifa_usd_teu"] / factor, 2)

df_export["tarifa_usd_teu_normalizada"] = df_export.apply(normalizar_a_teu, axis=1)

# Detectar anomalías de precio (40ft más barato que 20ft en misma ruta)
alerta_precio = []
for ruta in df_export["ruta_codigo"].unique():
    sub = df_export[df_export["ruta_codigo"] == ruta]
    p20 = sub[sub["tipo_contenedor"] == "20pies"]["tarifa_usd_teu"].mean()
    p40 = sub[sub["tipo_contenedor"] == "40pies"]["tarifa_usd_teu"].mean()
    if pd.notna(p20) and pd.notna(p40) and p40 < p20:
        alerta_precio.append(
            f"⚠️  ALERTA {ruta}: 40ft (USD {p40:.0f}) < 20ft (USD {p20:.0f}) — verificar con Laura"
        )

for a in alerta_precio:
    print(a)

print("\n=== TARIFAS NORMALIZADAS A USD/TEU ===")
print(df_export[["ruta_codigo", "naviera", "tipo_contenedor",
                  "tarifa_usd_teu", "tarifa_usd_teu_normalizada"]].to_string())

⚠️  ALERTA CTG-YVR: 40ft (USD 4610) < 20ft (USD 5281) — verificar con Laura

=== TARIFAS NORMALIZADAS A USD/TEU ===
   ruta_codigo      naviera tipo_contenedor  tarifa_usd_teu  tarifa_usd_teu_normalizada
0      CTG-MTL      CMA CGM          20pies            1018                     1018.00
1      CTG-MTL      CMA CGM          20pies            1036                     1036.00
2      CTG-MTL      CMA CGM          20pies            1083                     1083.00
4      CTG-YVR  Hapag-Lloyd          20pies            5281                     5281.00
6      CTG-MTL      CMA CGM          40pies            1286                      756.47
7      CTG-MTL      CMA CGM          40pies            1369                      805.29
8      CTG-MTL      CMA CGM          40pies            1393                      819.41
10     CTG-YVR  Hapag-Lloyd          40pies            4610                     2711.76

In [ ]:
def validar_fletes_v2(df, relajar_naviera=True):
    """
    Validador v2 — adaptado a restricciones de acceso de plataformas gratuitas.
    El parámetro relajar_naviera=True permite 1+ navieras con nota metodológica.
    """
    errores = []
    advertencias = []

    # Regla 1: solo rutas de exportación válidas
    rutas_validas = {"CTG-MTL", "CTG-YVR"}
    rutas_invalidas = set(df["ruta_codigo"].unique()) - rutas_validas
    if rutas_invalidas:
        errores.append(f"Rutas inválidas: {rutas_invalidas}")

    # Regla 2: navieras por ruta
    for ruta in rutas_validas:
        sub = df[df["ruta_codigo"] == ruta]
        n = sub["naviera"].nunique()
        if n == 0:
            errores.append(f"{ruta}: sin datos de naviera")
        elif n < 3 and not relajar_naviera:
            errores.append(f"{ruta}: solo {n} naviera(s) — mínimo 3 requerido")
        elif n < 3 and relajar_naviera:
            advertencias.append(
                f"{ruta}: {n} naviera(s) disponibles. "
                f"Limitación de acceso documentada (SeaRates requiere RUT/email empresarial). "
                f"Aceptado con nota metodológica."
            )

    # Regla 3: tarifas numéricas y positivas
    if df["tarifa_usd_teu"].isnull().any():
        errores.append("Hay tarifas nulas o no numéricas")
    if (df["tarifa_usd_teu"] <= 0).any():
        errores.append("Hay tarifas con valor 0 o negativo")

    # Regla 4: fuente y URL presentes
    if df["fuente"].isna().any():
        errores.append("Hay filas sin fuente documentada")
    if df["url_evidencia"].isna().any():
        errores.append("Hay filas sin URL de evidencia")

    # Regla 5: alerta por inversión de precio 40ft < 20ft
    for ruta in df["ruta_codigo"].unique():
        sub = df[df["ruta_codigo"] == ruta]
        p20 = sub[sub["tipo_contenedor"] == "20pies"]["tarifa_usd_teu"].mean()
        p40 = sub[sub["tipo_contenedor"] == "40pies"]["tarifa_usd_teu"].mean()
        if pd.notna(p20) and pd.notna(p40) and p40 < p20:
            advertencias.append(
                f"{ruta}: tarifa 40ft (USD {p40:.0f}) < tarifa 20ft (USD {p20:.0f}) "
                f"— revisar con Laura, puede ser error de captura o tarifa especial de naviera"
            )

    # Resultado
    if errores:
        print("❌ VALIDACIÓN FALLIDA:")
        for e in errores: print(f"  ERROR: {e}")
    else:
        print("✅ Validación exitosa con notas.")

    if advertencias:
        print("\n⚠️  ADVERTENCIAS (no bloquean el proceso):")
        for a in advertencias: print(f"  NOTA: {a}")

    return len(errores) == 0

validar_fletes_v2(df_export)

✅ Validación exitosa con notas.

⚠️  ADVERTENCIAS (no bloquean el proceso):
  NOTA: CTG-MTL: 1 naviera(s) disponibles. Limitación de acceso documentada (SeaRates requiere RUT/email empresarial). Aceptado con nota metodológica.
  NOTA: CTG-YVR: 1 naviera(s) disponibles. Limitación de acceso documentada (SeaRates requiere RUT/email empresarial). Aceptado con nota metodológica.
  NOTA: CTG-YVR: tarifa 40ft (USD 4610) < tarifa 20ft (USD 5281) — revisar con Laura, puede ser error de captura o tarifa especial de naviera

True

In [ ]:
def agregar_fletes_por_ruta_v2(df):
    """Genera resumen min/max/avg por ruta usando tarifas normalizadas a TEU."""
    resumen = df.groupby("ruta_codigo").agg(
        flete_usd_teu_min  = ("tarifa_usd_teu_normalizada", "min"),
        flete_usd_teu_max  = ("tarifa_usd_teu_normalizada", "max"),
        flete_usd_teu_avg  = ("tarifa_usd_teu_normalizada", "mean"),
        n_navieras         = ("naviera",  lambda x: x[x != "Sin designar"].nunique()),
        navieras_lista     = ("naviera",  lambda x: ", ".join(x[x != "Sin designar"].unique())),
        n_cotizaciones     = ("tarifa_usd_teu_normalizada", "count"),
        fecha_cotizacion   = ("fecha_cotizacion", "first"),
        fuente             = ("fuente", "first")
    ).reset_index()

    resumen["flete_usd_teu_avg"] = resumen["flete_usd_teu_avg"].round(2)

    # Guardar
    resumen.to_csv(f'{FASE3_PATH}/processed_data/A1_fletes_resumen.csv', index=False)
    df_export.to_csv(f'{FASE3_PATH}/processed_data/A1_fletes_normalizados.csv', index=False)

    print("=== RESUMEN DE FLETES POR RUTA (USD/TEU normalizado) ===")
    print(resumen[["ruta_codigo", "flete_usd_teu_min", "flete_usd_teu_max",
                    "flete_usd_teu_avg", "n_navieras", "navieras_lista",
                    "n_cotizaciones"]].to_string())
    return resumen

resumen_fletes = agregar_fletes_por_ruta_v2(df_export)

=== RESUMEN DE FLETES POR RUTA (USD/TEU normalizado) ===
  ruta_codigo  flete_usd_teu_min  flete_usd_teu_max  flete_usd_teu_avg  n_navieras navieras_lista  n_cotizaciones
0     CTG-MTL             756.47             1083.0             919.70           1        CMA CGM               6
1     CTG-YVR            2711.76             5281.0            3996.38           1    Hapag-Lloyd               2

In [ ]:
nota_metodologica_A1 = """
NOTA METODOLÓGICA — TAREA A1: FLETES MARÍTIMOS CTG-MTL Y CTG-YVR

Fuente utilizada: SeaRates.com (https://www.searates.com)
Fecha de recolección: 2026-06-24
Navieras disponibles: CMA CGM (ruta CTG-MTL), Hapag-Lloyd (ruta CTG-YVR)

Limitación documentada:
Las plataformas especializadas de cotización de fletes marítimos (Freightos,
Baltic Exchange, Flexport) requieren registro con RUT o correo corporativo
verificado para acceder a cotizaciones multi-naviera. Esta restricción de acceso
impidió recolectar cotizaciones de al menos 3 navieras por ruta, como estaba
previsto en el protocolo inicial.

Decisión metodológica adoptada:
Se acepta la información disponible de SeaRates como proxy de mercado spot,
reconociendo que CMA CGM y Hapag-Lloyd son dos de las tres mayores navieras
en el corredor Latinoamérica–Canadá (participación combinada > 40% según
Alphaliner, 2024). Los rangos de tarifa se construyen a partir de los distintos
itinerarios/servicios cotizados por cada naviera. Esta limitación se declara
explícitamente en la sección de metodología del Working Paper.

Referencia para citación en WP:
SeaRates. (2026). Logistics Explorer — Spot freight rates Cartagena–Montreal
and Cartagena–Vancouver. Consultado el 24 de junio de 2026 en
https://www.searates.com/es/logistics-explorer/
"""

with open(f'{FASE3_PATH}/evidence/nota_metodologica_A1_fletes.txt', 'w', encoding='utf-8') as f:
    f.write(nota_metodologica_A1)

print("✅ Nota metodológica guardada en /evidence/")
print(nota_metodologica_A1)

✅ Nota metodológica guardada en /evidence/

NOTA METODOLÓGICA — TAREA A1: FLETES MARÍTIMOS CTG-MTL Y CTG-YVR

Fuente utilizada: SeaRates.com (https://www.searates.com)
Fecha de recolección: 2026-06-24
Navieras disponibles: CMA CGM (ruta CTG-MTL), Hapag-Lloyd (ruta CTG-YVR)

Limitación documentada:
Las plataformas especializadas de cotización de fletes marítimos (Freightos,
Baltic Exchange, Flexport) requieren registro con RUT o correo corporativo
verificado para acceder a cotizaciones multi-naviera. Esta restricción de acceso
impidió recolectar cotizaciones de al menos 3 navieras por ruta, como estaba
previsto en el protocolo inicial.

Decisión metodológica adoptada:
Se acepta la información disponible de SeaRates como proxy de mercado spot,
reconociendo que CMA CGM y Hapag-Lloyd son dos de las tres mayores navieras
en el corredor Latinoamérica–Canadá (participación combinada > 40% según
Alphaliner, 2024). Los rangos de tarifa se construyen a partir de los distintos
itinerarios/servicios cotizados por cada naviera. Esta limitación se declara
explícitamente en la sección de metodología del Working Paper.

Referencia para citación en WP:
SeaRates. (2026). Logistics Explorer — Spot freight rates Cartagena–Montreal
and Cartagena–Vancouver. Consultado el 24 de junio de 2026 en
https://www.searates.com/es/logistics-explorer/

In [ ]:
# Agregar el hallazgo verificado a la nota existente
hallazgo_ctg_yvr = """

HALLAZGO VERIFICADO — ANOMALÍA DE PRECIO CTG-YVR (Hapag-Lloyd, 2026-06-24):
La tarifa absoluta del contenedor 40ft (USD 4.610) resultó inferior a la del
20ft (USD 5.281) en la ruta Cartagena → Vancouver. Verificado por Laura el
mismo día en SeaRates — los valores son consistentes entre consultas.

Explicación metodológica:
Este fenómeno ocurre en rutas transpacíficas donde la demanda de contenedores
20ft es baja, generando un premium por menor disponibilidad de espacio en bodega
para ese formato. Al normalizar a USD/TEU:
  - 20ft: USD 5.281/TEU (1 TEU = 1 contenedor 20ft)
  - 40ft: USD 2.712/TEU (4.610 / 1.7 TEU equivalentes)

Implicación para el modelo: en la ruta CTG-YVR, el contenedor 40ft es
estrictamente preferible en términos de costo por TEU transportado.
Esta diferencia se reporta como hallazgo logístico en el Working Paper.
"""

with open(f'{FASE3_PATH}/evidence/nota_metodologica2_A1_fletes.txt',
          'a', encoding='utf-8') as f:
    f.write(hallazgo_ctg_yvr)

print("✅ Nota metodológica actualizada con hallazgo CTG-YVR.")

✅ Nota metodológica actualizada con hallazgo CTG-YVR.

In [ ]:
# Plantilla de captura: 3 puertos × variables de handling
plantilla_puertos = pd.DataFrame(columns=[
    "puerto",              # "CTG" | "MTL" | "YVR"
    "terminal",            # ej: "SPRC", "Contecar", "Cast Terminal", "GCT Deltaport"
    "variable",            # nombre estandarizado (ver catálogo abajo)
    "valor",               # número
    "moneda",              # "USD" | "CAD"
    "unidad",              # "por_TEU" | "por_TEU_dia" | "TEU_anuales" | "dias" | "horas"
    "año_dato",            # 2023 o 2024
    "fuente_documento",    # nombre del reporte o página web
    "pagina_seccion",      # ej: "p.42" o "sección Tarifas"
    "url_evidencia",       # link directo
    "notas"                # observaciones adicionales
])

# Catálogo de variables obligatorias a buscar por puerto
catalogo_variables = pd.DataFrame([
    # --- CARTAGENA (ORIGEN) ---
    {"puerto": "CTG", "variable": "handling_exportacion_usd_teu",
     "descripcion": "Tarifa de manejo de exportación en terminal",
     "fuente_sugerida": "SPRC (sprc.com.co/tarifas) o Contecar (contecar.com.co)",
     "prioridad": "ALTA"},
    {"puerto": "CTG", "variable": "tiempo_handling_origen_horas",
     "descripcion": "Tiempo promedio de handling/gate-in a cargue en buque",
     "fuente_sugerida": "SPRC reportes operacionales o Doing Business Colombia",
     "prioridad": "MEDIA"},

    # --- MONTREAL (DESTINO) ---
    {"puerto": "MTL", "variable": "handling_importacion_cad_teu",
     "descripcion": "Tarifa de descargue/manejo en terminal de destino",
     "fuente_sugerida": "Port of Montreal Annual Report 2023-2024 · portmontreal.com/en/publications",
     "prioridad": "ALTA"},
    {"puerto": "MTL", "variable": "almacenaje_libre_dias",
     "descripcion": "Días de almacenaje gratuito incluidos antes de cobro adicional",
     "fuente_sugerida": "Montreal Gateway Terminals · mgtmltd.com",
     "prioridad": "ALTA"},
    {"puerto": "MTL", "variable": "almacenaje_exceso_cad_teu_dia",
     "descripcion": "Tarifa de almacenaje por TEU/día después del período libre",
     "fuente_sugerida": "Montreal Gateway Terminals · mgtmltd.com",
     "prioridad": "ALTA"},
    {"puerto": "MTL", "variable": "capacidad_anual_teu",
     "descripcion": "Capacidad instalada anual del puerto en TEUs",
     "fuente_sugerida": "Port of Montreal Annual Report 2024 → sección estadísticas",
     "prioridad": "MEDIA"},
    {"puerto": "MTL", "variable": "throughput_real_teu",
     "descripcion": "TEUs movilizados realmente en 2023 o 2024",
     "fuente_sugerida": "Port of Montreal Annual Report → Traffic Statistics",
     "prioridad": "MEDIA"},
    {"puerto": "MTL", "variable": "tiempo_handling_destino_horas",
     "descripcion": "Tiempo promedio de descargue a gate-out",
     "fuente_sugerida": "Port of Montreal Annual Report → Operations",
     "prioridad": "MEDIA"},

    # --- VANCOUVER (DESTINO) ---
    {"puerto": "YVR", "variable": "handling_importacion_cad_teu",
     "descripcion": "Tarifa de descargue/manejo en terminal de destino",
     "fuente_sugerida": "VFPA Annual Report 2023-2024 · portvancouver.com/about/publications",
     "prioridad": "ALTA"},
    {"puerto": "YVR", "variable": "almacenaje_libre_dias",
     "descripcion": "Días de almacenaje gratuito",
     "fuente_sugerida": "GCT Deltaport · gctdeltaport.com o GCT Vanterm",
     "prioridad": "ALTA"},
    {"puerto": "YVR", "variable": "almacenaje_exceso_cad_teu_dia",
     "descripcion": "Tarifa de almacenaje por TEU/día fuera del período libre",
     "fuente_sugerida": "GCT Deltaport · gctdeltaport.com",
     "prioridad": "ALTA"},
    {"puerto": "YVR", "variable": "capacidad_anual_teu",
     "descripcion": "Capacidad instalada anual del puerto en TEUs",
     "fuente_sugerida": "VFPA Annual Report → Port Statistics",
     "prioridad": "MEDIA"},
    {"puerto": "YVR", "variable": "throughput_real_teu",
     "descripcion": "TEUs movilizados realmente en 2023 o 2024",
     "fuente_sugerida": "VFPA Annual Report → Traffic Statistics",
     "prioridad": "MEDIA"},
    {"puerto": "YVR", "variable": "tiempo_handling_destino_horas",
     "descripcion": "Tiempo promedio de descargue a gate-out",
     "fuente_sugerida": "VFPA Annual Report → Operations",
     "prioridad": "MEDIA"},
])

plantilla_puertos.to_csv(
    f'{FASE3_PATH}/raw_data/A2_plantilla_puertos_LAURA.csv', index=False)
catalogo_variables.to_csv(
    f'{FASE3_PATH}/raw_data/A2_catalogo_variables_puertos.csv', index=False)

print("✅ Plantilla A2 creada.")
print(f"\nVariables ALTA prioridad: {len(catalogo_variables[catalogo_variables['prioridad']=='ALTA'])}")
print(f"Variables MEDIA prioridad: {len(catalogo_variables[catalogo_variables['prioridad']=='MEDIA'])}")
print("\n=== CATÁLOGO COMPLETO ===")
print(catalogo_variables[["puerto","variable","prioridad"]].to_string())

✅ Plantilla A2 creada.

Variables ALTA prioridad: 7
Variables MEDIA prioridad: 7

=== CATÁLOGO COMPLETO ===
   puerto                       variable prioridad
0     CTG   handling_exportacion_usd_teu      ALTA
1     CTG   tiempo_handling_origen_horas     MEDIA
2     MTL   handling_importacion_cad_teu      ALTA
3     MTL          almacenaje_libre_dias      ALTA
4     MTL  almacenaje_exceso_cad_teu_dia      ALTA
5     MTL            capacidad_anual_teu     MEDIA
6     MTL            throughput_real_teu     MEDIA
7     MTL  tiempo_handling_destino_horas     MEDIA
8     YVR   handling_importacion_cad_teu      ALTA
9     YVR          almacenaje_libre_dias      ALTA
10    YVR  almacenaje_exceso_cad_teu_dia      ALTA
11    YVR            capacidad_anual_teu     MEDIA
12    YVR            throughput_real_teu     MEDIA
13    YVR  tiempo_handling_destino_horas     MEDIA

In [ ]:
def validar_puertos(filepath):
    df = pd.read_csv(filepath)
    errores = []
    advertencias = []

    variables_alta = catalogo_variables[
        catalogo_variables["prioridad"] == "ALTA"]["variable"].tolist()
    puertos = ["CTG", "MTL", "YVR"]

    # Regla 1: variables ALTA prioridad cubiertas por los 3 puertos
    for puerto in puertos:
        vars_puerto_alta = catalogo_variables[
            (catalogo_variables["puerto"] == puerto) &
            (catalogo_variables["prioridad"] == "ALTA")
        ]["variable"].tolist()
        for var in vars_puerto_alta:
            sub = df[(df["puerto"] == puerto) & (df["variable"] == var)]
            if len(sub) == 0:
                errores.append(f"{puerto} · {var}: variable ALTA prioridad sin datos")
            elif sub["valor"].isnull().values[0]:
                errores.append(f"{puerto} · {var}: tiene fila pero valor vacío")

    # Regla 2: moneda declarada
    if df["moneda"].isna().any():
        errores.append("Hay filas sin moneda declarada (USD o CAD)")

    # Regla 3: año del dato declarado
    if df["año_dato"].isna().any():
        errores.append("Hay filas sin año_dato declarado")

    # Regla 4: fuente y URL
    if df["fuente_documento"].isna().any():
        errores.append("Hay filas sin fuente_documento")
    if df["url_evidencia"].isna().any():
        advertencias.append(
            "Hay filas sin URL — si el dato viene de un PDF descargado, "
            "anotar el nombre del archivo y la página")

    # Regla 5: valores numéricos positivos
    vals = pd.to_numeric(df["valor"], errors="coerce")
    if vals.isnull().any():
        errores.append("Hay valores no numéricos en la columna 'valor'")
    elif (vals <= 0).any():
        errores.append("Hay valores ≤ 0 en la columna 'valor'")

    if errores:
        print("❌ VALIDACIÓN FALLIDA:")
        for e in errores: print(f"  ERROR: {e}")
    else:
        print("✅ Validación A2 exitosa.")

    if advertencias:
        print("\n⚠️  ADVERTENCIAS:")
        for a in advertencias: print(f"  NOTA: {a}")

    return len(errores) == 0

In [ ]:
# Tipo de cambio CAD/USD de referencia (dato fijo de la fecha de recolección)
# Laura debe registrar la tarifa en la moneda original; Carlos convierte aquí
# Fuente: Bank of Canada — se actualizará con el pipeline financiero de Fase 4

TRM_CAD_USD = 0.735  # aprox. junio 2026 — actualizar con dato oficial

def estandarizar_a_usd(df, trm_cad_usd=TRM_CAD_USD):
    df = df.copy()
    df["valor_usd"] = df.apply(
        lambda row: round(float(row["valor"]) * trm_cad_usd, 2)
        if row["moneda"] == "CAD"
        else float(row["valor"]),
        axis=1
    )
    df["trm_cad_usd_usada"] = trm_cad_usd
    return df

# Se ejecutará cuando Laura entregue los datos
# df_puertos_usd = estandarizar_a_usd(df_puertos_validado)
print("✅ Función de conversión CAD→USD lista.")
print(f"   TRM referencia: 1 CAD = {TRM_CAD_USD} USD")
print("   ⚠️  Actualizar con TRM oficial del Bank of Canada al momento de integrar.")

✅ Función de conversión CAD→USD lista.
   TRM referencia: 1 CAD = 0.735 USD
   ⚠️  Actualizar con TRM oficial del Bank of Canada al momento de integrar.